Unfortunately for my theories, Nochli was definitely evil.


[Marvin's had been observing them on public camera feeds, and then expanded into hacking camera feeds. They sometimes descended from their balloon-fortresses on winged creatures, and interrogated random people, using displayed Patterns and whistled commands. We had video from reverted futures of them vivisecting people]

["time travel detection" based on camera feeds: everything the camera sees, the server sends back in time by N seconds and then does a short "stable time loop" with the information. If it has already done so and sees a DIFFERENT thing next time, it also sends back the different thing, creating an additional record. Thus, it detects any time travel that modified the camera view during a window of N seconds and did not also modify the history of the computer prior to those N seconds (which would invalidate the stable time loop also). To make a "paradox trap", you just do a non-converging loop whenever you detect such a difference; of course, for now, we had to make sure we did NOT accidentally use any of these as a paradox trap, because that would be an instant lose condition]

[When Marvins had first deployed the "time travel detection", it had generated such a huge amount of data that they assumed it must have been a bug. But every time Nochli interacted with people… [When I looked at just one of the many examples, it really drove home] how utterly helpless any [ethra/ordinary human] was against fully developed alchiia. Even the one ordinary conversation had [thousands] of timeline branches, the Nochli trying out countless different details of wording and mannerisms to optimize how the victim would react, making quick changes and reverting them using the time machines inside their brains, so quickly that some of the data was lost because of the network latency. In between, they did short branches where they [used custom organisms that were designed to analyze people by digesting their brain and body] – Alpha had insisted that every subsequent Marvin be standing with a vomit bucket the first time they watched – disturbingly, the victims didn't scream or struggle while they were being torn open (because the organisms anesthetize them to avoid random spasms confusing the data). But from the victim's perspective, in the final timeline, Nochli were superhumanly friendly and reassuring; any ordinary human would be putty in their hands, even WITHOUT the huvith. And the most ominous thing was, this was what they did during an extremely low stakes interaction – imagine what they could bring to bear if they were actually threatened.]

[Marvins catch on that a bunch of the kidnapping targets are tech experts; maybe they passively detect cell phone communications from inside the airships, use social network information to predict who will be kidnapped next, and hack their phones to exfiltrate the interrogations; in this manner they learn that Nochli are collecting high-quality recordings from the history of Salnthu, and prioritizing replication/availability over privacy. Marvin's begin intercepting the radio transmissions between the airships, to download the recordings


[What follows is a summary of the history, not exactly reflecting the order I want to explain it, or the attitude/perspective I want to use to explain it]

[the history goes: there was a king who thought he was better than everyone else, who duplicated himself a bunch of times; but Nochli wasn't the king, he was a scribe. As the king duplicated himself, he had also duplicated Nochli, to organize his operations. But the difference between a king and a scribe is, a king isn't accustomed to working efficiently with other people as equals. As the king duplicated himself more and more, resentment began between different factions of the king, but the copies of Nochli always worked together with each other. Soon the Nochlis realized that the king's infighting was slowly getting them wiped out (by better-organized rivals), which would drive them to extinction if Nochli didn't do something, so Nochli worked together to kill (poison?) all the copies of the king and take over the faction themselves, collectively looking out for the interests of Nochli as a whole. And that's how a scribe and historian ended up being in charge of an entire faction]

[The original human Nochli doesn't seem especially evil. He grew up upper-class in that society, and is notable for being intrinsically interested in history and scholarship. He travels to record the expertise of artisans, and pays them well for it, and respects the boundaries of those who wants to keep their secrets. He's opportunistic in a positive sense, leaving situations that don't work for him instead of making a fight about it, and maintains highly trusting relationships on an individual level; on the other hand, he doesn't rock the boat of the oppression he benefits from (he is kind and pays well to his own servants, who are theoretically free to quit, but he also does logistics for construction work performed by slaves, and only improves their lot when he sees a easy opportunity to, which is infrequent). If he never abused anyone individually back then, how did he end up vivisecting people later? Maybe it's because he hadn't found the Ring of Gyges yet…]

[Human duplication was already known in his childhood, but it took decades to become the order of the whole world – in the meantime there were quite a few localized cases of mass duplication, but it usually resulted in disaster because of logistics issues (e.g. duplicating people faster than you can duplicate food for them, and then rebellion by the starving people breaks the human and material infrastructure that was being used to make more time machines.) Nochli's logistics skills contributed to pioneering more stable duplication (which the king later took advantage of), although Nochli wasn't quite an inventor, he mainly collected knowledge from others.]

[The camera was impressively neutral, watching even the everyday moments of his life; the cameraflies had no concern for privacy. Other ones viewed society as a whole, both in Salnthu and Huvinthu]

[Once the world was dominated by the factions of duplicates, Nochli was largely isolationist, defending his own territory vigorously but staying out of the conflicts of other factions that rose and fell. He used knowledge of historical conflicts to make sure he was not a desirable target to conquer, and make sure to know the strengths and weaknesses of each of his rivals, in case they did attempt it. As before, he didn't make major innovations himself, but copied and perfected the innovations by other factions. Like almost every faction, he maintained an ever-steeper power imbalance between the time travellers (his selves) and the non-time travellers he managed; Nochli maintained humanlike relationships with some of them, but those relationships steadily got more coercive and illusionary; security motivations caused Nochli to further and further restrict their access to the time machines, and by the end, anytime Nochli interacted with a non-time traveller as if there were equals, it was basically role-playing a relationship between equals]

[Like Kayla, he made his tree immortal by duplicating copies of early selves]

[Maybe he used copies of people he'd once had good relationships with, to role-play those relationships? But it got more and more isolating, because he couldn't actually share his current life with them. And as his appearance got less and less human, there was more explaining to do. Meanwhile, major advancements in brain surgery and biological treatments (which he learned from other factions, experimenting on non-Nochlis, and experimenting on Nochlis) allowed him to relieve the physical desires by removing them rather than indulging them, allowing him to become more focused in his pursuit of studies (like EliDupree, making himself more stimulated by the idea of things rather than the physical acts); he heavily optimized himself for his particular situation of "studying history using old time machines", "performing unethical breeding experiments on both humans and other organisms", and "being in constant conflict with other factions of time travellers"]

[How did this change when he copied the immortality tech from Ontoh's faction?]

[Ultimately he obsessed over Project Huvith; Marvin sees this via a bunch of physical details of the project, so it takes a while to infer what the motivations were, but they are basically (1) because of his long-term thinking, Nochli realizes the inevitably that some other faction will eventually make a superweapon and wipe him out, unless there is first a complete resolution to the conflicts; (2) he still remembers how he grew up without much time travel, and misses the human relationships from that world (and it's hard to replicate them; he makes experimental societies (like Nemesis from Odyssey) but they basically have to live their entire lives in artificial environments inside time dilation chambers), and Nochli's overarching organizational approach favors spending spacetime on useful experiments rather than indulging in role-playing (in fact, perhaps he has had to take active steps to prevent Nochlis from spending all their time rewatching past events – theoretically motivated by external threats of course)]

[Physically, Project Huvith had multiple research aspects: (1) finding the oldest time machines using repeated, brief excursions into the past; (2) developing the huvith themselves through repeated breeding experiments on artificial societies; (3) developing the assemblages of time machines (the collapsible ones for transporting large amounts of stuff in the tiny original time machine, the nested budget-extenders, and the synchronization system)]

[here's where it gets plot-relevant: the synchronization system. In order to synchronize, Huvinthu must witness the same first-departure as Salnthu did, except with the Huvinthu instance of the ancient time machine instead of the Salnthu instance; the only way to do this is to copy the first-departure from Salnthu, but swap the time machines. So the departure takes place inside a pair of sealed chambers – the time travellers wait in the first chamber while the ancient time machine is placed in the second chamber from the other side, then they open the second chamber and use whatever time machine is there. To synchronize, the Huvinthu Nochlis first go back to and "steal" this entire assembly back to Huvinthu (before the ancient time machine is inserted), then place the Huvinthu instance in the second chamber and seal it. If this doesn't go exactly right, you get a paradox, but that's not a huge problem because the overseers on Salnthu can just initiate a retry from a recent backup of Huvinthu]

[can Ontoh be prevented from understanding the synchronization system? It would certainly be the most secret part of the project – from the perspective of rival factions, the other parts don't necessarily indicate that they're about to perform a coup over the world. The huvith are useful for managing non-time travellers, the historical excursions are a known quirk of Nochli, the collapsible time machines and budget-extenders are probably just improvements of existing technology… but the synchronization chambers have little use in Salnthu (why do you care to send a physical copy of something from the present into the past and have it stick, when you can't go very far back anyway because of paradox traps? If you wanted to try something destructive and obtain the resulting physical entity, you could just do it in an alternate past and "steal" it). So Nochli might be careful about access to the knowledge of the synchronization chamber project, such that the large majority of Nochli actually DON'T know how total the coup is going to be, and think it is just a particularly large historical excursion (and only the few Nochli who were "in the know" would actually go on the excursion themselves); Ontoh could plausibly have only learned this more widespread knowledge, then followed one of the various teams who were loading the goods for the excursion (Ontoh would then pass through the synchronization chambers and be able to describe them to the protagonists without knowing what they were for)]
