Unfortunately for my theories, Nochli was definitely evil.


[Marvin's had been observing them on public camera feeds, and then expanded into hacking camera feeds. They sometimes descended from their balloon-fortresses on winged creatures, and interrogated random people, using displayed Patterns and whistled commands. We had video from reverted futures of them vivisecting people]

["time travel detection" based on camera feeds: everything the camera sees, the server sends back in time by N seconds and then does a short "stable time loop" with the information. If it has already done so and sees a DIFFERENT thing next time, it also sends back the different thing, creating an additional record. Thus, it detects any time travel that modified the camera view during a window of N seconds and did not also modify the history of the computer prior to those N seconds (which would invalidate the stable time loop also). To make a "paradox trap", you just do a non-converging loop whenever you detect such a difference; of course, for now, we had to make sure we did NOT accidentally use any of these as a paradox trap, because that would be an instant lose condition]

[When Marvins had first deployed the "time travel detection", it had generated such a huge amount of data that they assumed it must have been a bug. But every time Nochli interacted with people… [When I looked at just one of the many examples, it really drove home] how utterly helpless any [ethra/ordinary human] was against fully developed alchiia. Even the one ordinary conversation had [thousands] of timeline branches, the Nochli trying out countless different details of wording and mannerisms to optimize how the victim would react, making quick changes and reverting them using the time machines inside their brains, so quickly that some of the data was lost because of the network latency. In between, they did short branches where they [used custom organisms that were designed to analyze people by digesting their brain and body] – Alpha had insisted that every subsequent Marvin be standing with a vomit bucket the first time they watched – disturbingly, the victims didn't scream or struggle while they were being torn open (because the organisms anesthetize them to avoid random spasms confusing the data). But from the victim's perspective, in the final timeline, Nochli were superhumanly friendly and reassuring; any ordinary human would be putty in their hands, even WITHOUT the huvith. And the most ominous thing was, this was what they did during an extremely low stakes interaction – imagine what they could bring to bear if they were actually threatened.]

[Marvins catch on that a bunch of the kidnapping targets are tech experts; maybe they passively detect cell phone communications from inside the airships, use social network information to predict who will be kidnapped next, and hack their phones to exfiltrate the interrogations; in this manner they learn that Nochli are collecting high-quality recordings from the history of Salnthu, and prioritizing replication/availability over privacy. Marvin's begin intercepting the radio transmissions between the airships, to download the recordings
