#!/usr/bin/python3
# -*- coding: utf-8 -*-




posts = [
{
"title": "Projects update 2017-10-18",
"tags": [],
"auto_paragraphs": True,
"ignore_for_random_post": True,
"ignore_for_page_numbering": True,
"blurb": "",
"contents":'''

This week's been a busy week. For one thing, I've all-but-completed Chapter 3 of <a href="/ravelling-wrath">Ravelling Wrath</a>! I almost decided to rush it out to post today, but I figured I should get someone to proofread it first. But it's very likely I can have it ready by next week.

For another, I've kept working on my music stuff! I can't explain all of it, but I did make <a href="/media/interval_optimized_1_hour.ogg">some neat procedurally-generated music that I can show you</a>. I initially made a 30 second clip of it, but a friend asked me to generate a one-hour version because it sounded relaxing, so one hour it is! It's generated by an algorithm that picks random pitches, then tweaks them until they sound consonant according to the <a href="https://en.wikipedia.org/wiki/Limit_(music)">odd limit</a> concept.

I also worked on drawing <a href="/comics">Voldemort's Children</a> a bit yesterday! I've had a lot of false starts in the past, so we'll have to see how it goes. This time, I think I've discovered that my idea of holding the stylus lightly was actually an <a href="https://en.wikipedia.org/wiki/Anti-pattern">anti-pattern</a>. Gripping it less hard gave me less control over it, which meant I ultimately used my muscles <em>more</em> to do the same amount of drawing.


''',
},

]

"""

#A template for new posts, which I copy each time I start one.
{
"title": "
"tags": [],
"auto_paragraphs": True,
"don't deploy": True,
"blurb": "",
"contents":'''

''',
},
"""
