#!/usr/bin/python3
# -*- coding: utf-8 -*-




posts = [
{
"title": "Projects update 2017-10-18",
"tags": [],
"auto_paragraphs": True,
"ignore_for_random_post": True,
"ignore_for_page_numbering": True,
"blurb": "",
"contents":'''

This week's been a busy week. For one thing, I've all-but-completed Chapter 3 of <a href="/ravelling-wrath">Ravelling Wrath</a>! I almost decided to rush it out to post today, but I figured I should get someone to proofread it first. But it's very likely I can have it ready by next week.

For another, I've kept working on my music stuff! I can't explain all of it, but I did make <a href="/media/interval_optimized_1_hour.ogg">some neat procedurally-generated music that I can show you</a>. I initially made a 30 second clip of it, but a friend asked me to generate a one-hour version because it sounded relaxing, so one hour it is! It's generated by an algorithm that picks random pitches, then tweaks them until they sound consonant according to the <a href="https://en.wikipedia.org/wiki/Limit_(music)">odd limit</a> concept.

I also worked on drawing <a href="/comics">Voldemort's Children</a> a bit yesterday! I've had a lot of false starts in the past, so we'll have to see how it goes. This time, I think I've discovered that my idea of holding the stylus lightly was actually an <a href="https://en.wikipedia.org/wiki/Anti-pattern">anti-pattern</a>. Gripping it less hard gave me less control over it, which meant I ultimately used my muscles <em>more</em> to do the same amount of drawing.


''',
},

{
"title": "Projects update 2017-11-01",
"tags": [],
"auto_paragraphs": True,
"ignore_for_random_post": True,
"ignore_for_page_numbering": True,
"blurb": "",
"contents":'''

My music generation has seen a lot of progress this week! <a href="https://soundcloud.com/elidupree">I made a Soundcloud page to show off some of the best things the system has generated.</a>

I've already gotten to work on Chapter 4 of <a href="/ravelling-wrath">Ravelling Wrath</a>! It's around 1600 words now. Hopefully, I won't leave you all hanging for months like I did for the last chapter!

Finally, I've been making some slow progress on drawing <a href="/comics">Voldemort's Children</a>. It's not much, but I've managed to draw for 10 minutes on multiple days in a row without hurting myself, which is more than I've been able to for a long time. So maybe this is a sign of long-term improvement.


''',
},
{
"title": "Projects update 2017-11-08",
"tags": [],
"auto_paragraphs": True,
"ignore_for_random_post": True,
"ignore_for_page_numbering": True,
"blurb": "",
"contents":'''

I've been very lethargic this week. I've tried to get myself to work on my projects, but I just haven't been able to. Both writing and programming are types of creative work that I can't do right now.

However! Drawing <a href="/comics">Voldemort's Children</a> is different, because I already wrote all the dialogue and sketched all the remaining pages. All I have to do is draw, not think about what to draw. And my hands have continued getting better. I've been regularly doing <em>two</em> 10-minute drawing sessions each day, and I'm on track to increase that. I've completed the line-drawing stage of about 3 pages in 2 weeks. There's a bunch more work after the line drawing, but if I'm lucky, I might even be able to start fully completing a page per week soon!

''',
},

{
"title": "Empathy and its Tricky Relationship with Goodness",
"tags": ["neurodiversity"],
"auto_paragraphs": True,
"don't deploy": True,
"blurb": "",
"contents":'''
Maybe you're someone with a lot of <a href="https://en.wikipedia.org/wiki/Affective_empathy">affective empathy</a> – when you since other people having feelings, you have a lot of feelings yourself. Or maybe you're more like me, and don't have so much.

A lot of people talk as if <strong>empathy</strong> is the same thing as <strong>goodness</strong>. Maybe you've said some things like that yourself without thinking about it. In this line of thinking, saying that someone has no empathy is the same as saying they're an evil person. Naturally, this bugs me because I don't want to be called an evil person. But there are also some subtler problems that you might not think of at first:
<ul class="big_list">
<li>If being empathetic is automatically good, that makes it harder to talk about how empathy might lead you to hurt people, and how to avoid that problem.</li>
<li>If being unempathetic is automatically bad, that forces unempathetic people to <em>pretend</em> to be empathetic, instead of learning the unique ways of doing good that are easier without empathy.
</ul>

<h2>How to stop your empathy from hurting people</h2>

If you feel someone else's distress, it can motivate you to help them. Helping people is good! Unfortunately, empathetic people can also have a hard time <em>coping</em> with others' distress. And I've seen a lot of coping strategies that actually end up hurting other people.

You may have used some of these yourself. They're not <em>good</em>, but they are understandable responses. If these sound like you, I hope to offer you a better way rather than judging you harshly.

<h3>Avoiding</h3>

Alice and Bob are friends. Alice has been upset about something for a long time. Bob is very empathetic, and has been listening to Alice's woes and providing emotional support. Even when Bob is tired, ze feels like ze needs to keep helping Alice. But finally, Bob gets overwhelmed. So Bob starts avoiding Alice entirely, so that ze doesn't have to deal with Alice's distress.

Worse yet, because Bob thinks it's <em>wrong</em> to avoid Alice, Bob feels like ze needs to come up with a <em>justification</em> for avoiding Alice. Bob comes up with this: "Alice is just a negative person who will always drag other people down, no matter how much you try to help." When Bob gives this justification to other people, that implicitly encourages other people to avoid helping Alice, too. Alice gets more isolated, which makes things worse.

Notice that everything Bob does here is motivated by empathy! But no one says "people in society are too empathetic, and that's why suffering people are isolated".

So, what can you do instead? You might be thinking "Don't make cruel justifications", which would be a good change, but it doesn't fix the whole problem. I'd like to focus on something near the beginning – Bob's decision to keep helping Alice even when Bob was already tired. At that moment, Bob is thinking, "Alice needs help". But Bob hasn't thought ahead to the rest of what will happen if Bob burns zemself out, which actually makes things <em>worse</em> for Alice. At this point, it would be a better to think "It looks like this is going to be an ongoing situation. Is the way I'm supporting Alice sustainable for me? What ways can I support Alice without burning out?" After thinking about this, you might say something like, "Alice, I absolutely think you deserve support on this, but I'm starting to get overwhelmed. I can still listen when we meet on Saturday, but I'll definitely get burned out if we keep talking about this issue every day, and then I won't be able to help <em>you</em> with it, either."

[find boundary and stick to it; emotional labor?]

<ul class="big_list">
<li>You might avoid distress by

Avoiding distressed people so you don't have to interact with them.


Worse yet justification that blames another person
</li>
<li>
You might avoid distress by refusing to <em>believe</em> that the other person is in distress.
</li>
<li>
Trying to fix problems impatiently
</li>
</ul>


''',
},

]

"""

#A template for new posts, which I copy each time I start one.
{
"title": "
"tags": [],
"auto_paragraphs": True,
"don't deploy": True,
"blurb": "",
"contents":'''

''',
},
"""
